name: Update key currency info

on:
  schedule:
  - cron: "0/5 * * * *"

env:
  LEAGUE: Kalandra

jobs:
  update-key-curr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.KEY }}
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Fetch currency data from ninja and save into file
        run: curl https://poe.ninja/api/data/CurrencyOverview\?league\=$LEAGUE\&type\=Currency\&language\=ko > fetched.json
      - name: Extract key currency info from file
        run: | 
          backup_file=key-curr_$(date +%s).json
          mv key-curr.json backup/$backup_file
          jq '[.lines[] | select( .detailsId == "divine-orb" or .detailsId == "exalted-orb" ) | { id:.detailsId, chaosEquivalent:.chaosEquivalent, _t:.pay.sample_time_utc }]' fetched.json > key-curr.json
          rm fetched.json
      - name: Commit result
        run: |
          git config --global user.email "znoine+githubaction@gmail.com"
          git config --global user.name "znoine_githubaction"
          git add .
          git commit -m "action: Update key currency info"
          git push
